const state = {
  states: [
    {
      'key': 1, 'value': '100', 'disp': 'Scale',
      'label': 'GB_NM_PER_PIXEL', 'units': 'nm/pixel',
      'size': [
        1,
        4,
      ],
      'bytes': 8,
      'class': 'char',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '1200', 'disp': 'Time Interval',
      'label': 'GB_TIME_INTERVAL', 'units': 's',
      'size': [
        1,
        4,
      ],
      'bytes': 8,
      'class': 'char',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_Lmax',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_LmaxF',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_Lmin',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_LminF',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_bead_file_list',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_bead_file_num',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_blurF',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_blurred_mt_imgs',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_imagej_tf_file',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_is_preprocessed',
      'size': [
        1,
        1,
      ],
      'bytes': 8,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_map_file',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_map_imgs',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_mt_file',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_mt_imgs',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_mt_lines',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_mt_minus_params',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_mt_plus_params',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_normed_mt_imgs',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_params',
      'size': [
        1,
        1,
      ],
      'bytes': 1656,
      'class': 'struct',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_skel',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_skel_lines',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_tform',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
    {
      'key': 1, 'value': '', 'disp': '',
      'label': 'gb_theta',
      'size': [
        0,
        0,
      ],
      'bytes': 0,
      'class': 'double',
      'global': true,
      'sparse': false,
      'complex': false,
      'nesting': {
        'function': '',
        'level': 0,
      },
      'persistent': false,
    },
  ],
};

export default {
  state,
};
